<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,7,1,'QmFubmVy');
$cfg_Cs[2]=array(0,1,1,'5aqS5L2T5oql6YGT');
$cfg_Cs[3]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[5]=array(0,18,1,'6aG555uu5qGI5L6L');
$cfg_Cs[6]=array(5,18,1,'5paH5YyW');
$cfg_Cs[7]=array(5,18,1,'5Lya5omA');
$cfg_Cs[8]=array(5,18,1,'5ZWG5Lia');
$cfg_Cs[9]=array(5,18,1,'5Yqe5YWs');
$cfg_Cs[10]=array(5,18,1,'5pS56YCg');
$cfg_Cs[11]=array(5,18,1,'5L2P5a6F');
$cfg_Cs[12]=array(0,19,1,'5qC45b+D5Zui6Zif');
?>