
<field:message itemname="留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="500" page="">
</field:message>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:company itemname="公司" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:contact itemname="联系方式" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:add_time itemname="提交时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:add_time>
