<field:piclinks itemname="链接地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="500" page="">
</field:piclinks>
<field:islink itemname="是否快商通" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="true,false"  maxlength="250" page="">
</field:islink>
<field:video itemname="视频" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:video>
<field:type itemname="选择类型" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="picture,video"  maxlength="250" page="">
</field:type>
