<a href="[field:arcurl/]">
          <div class="list_left_date">
            <p>[field:pubdate function="MyDate('Y-m-d',@me)" /]</p>
            <span class="a_line"></span>
          </div>

          <div class="list_left_tit">
            <p>[field:title /]</p>
            <p>[field:description /]</p>
          </div>

          <div class="list_right_img">
            [field:picname/]
          </div>

          <div class="clear"></div>
        </a>