<?php
$z[0]=Array("arcurl","",9,24);
$z[0][4]=array();
$z[1]=Array("pubdate","",144,188);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y',@me)";
$z[2]=Array("pubdate","",238,284);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("title","",427,442);
$z[3][4]=array();
$z[4]=Array("description","",463,484);
$z[4][4]=array();
$z[5]=Array("picname","",572,588);
$z[5][4]=array();

?>