{dede:arclist row='6' orderby='pubdate' orderway='asc' addfields='city, project_name' channelid='18'}
        <div class="picture-grid-box">
          <a href="[field:arcurl/]">
            <picture>
              <img src="[field:picname/]" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>[field:city/]</p>
            <p>[field:project_name/]</p>
          </div>
        </div>
        {/dede:arclist}
        <div class="picture-grid-box grid-span">
          <a href="javascript:;">
            <picture>
              <img src="/templets/hsjzsj/src/assets/projects/2.jpg" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>南京</p>
            <p>紫金山庄</p>
          </div>
        </div>

        <div class="picture-grid-box grid-span-2">
          <a href="javascript:;">
            <picture>
              <img src="/templets/hsjzsj/src/assets/projects/3.jpg" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>深圳</p>
            <p>世界之窗</p>
          </div>
        </div>

        <div class="picture-grid-box">
          <a href="javascript:;">
            <picture>
              <img src="/templets/hsjzsj/src/assets/projects/4.jpg" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>上海</p>
            <p>汤臣一品</p>
          </div>
        </div>

        <div class="picture-grid-box">
          <a href="javascript:;">
            <picture>
              <img src="/templets/hsjzsj/src/assets/projects/5.jpg" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>上海</p>
            <p>汤臣一品</p>
          </div>
        </div>

        <div class="picture-grid-box">
          <a href="javascript:;">
            <picture>
              <img src="/templets/hsjzsj/src/assets/projects/6.jpg" alt="">
            </picture>
          </a>
          <div class="picture-info">
            <p>上海</p>
            <p>汤臣一品</p>
          </div>
        </div>