<?php
$z[0]=Array("arcurl","",9,24);
$z[0][4]=array();
$z[1]=Array("pubdate","",101,145);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y',@me)";
$z[2]=Array("pubdate","",166,212);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("title","",334,349);
$z[3][4]=array();
$z[4]=Array("description","",370,391);
$z[4][4]=array();
$z[5]=Array("picname","",479,495);
$z[5][4]=array();

?>