
<field:applyJob itemname="申请职位" autofield="1" type="text" isnull="true" default=""  maxlength="500" page="">
</field:applyJob>

<field:educateSchool itemname="毕业院校/学历" autofield="1" type="text" isnull="true" default=""  maxlength="500" page="">
</field:educateSchool>

<field:workYears itemname="工作年限" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:workYears>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>
