<?php
$z[0]=Array("arclist","\r\n        <div class=\"picture-grid-box\">\r\n          <a href=\"[field:arcurl/]\">\r\n            <picture>\r\n              <img src=\"[field:picname/]\" alt=\"\">\r\n            </picture>\r\n          </a>\r\n          <div class=\"picture-info\">\r\n            <p>{dede:field.city /}</p>\r\n            <p>{dede:field.project_name /}</p>\r\n          </div>\r\n        </div>\r\n        ",0,432);
$z[0][4]=array();
$z[0][4]['row']="6";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="asc";

?>