<a href="[field:arcurl/]" class="list_item">
          <div class="list_left_date">
            <p>[field:pubdate function="MyDate('Y-m-d',@me)" /]</p>
            <span class="a_line"></span>
          </div>

          <div class="list_left_tit">
            <p>[field:title /]</p>
            <p>[field:description /]</p>
          </div>

          <div class="list_right_img">
            <img src="[field:picname/]" alt="">
          </div>

          <div class="clear"></div>
        </a>