<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:project_type itemname="项目类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:project_type>

<field:project_name itemname="项目名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:project_name>

<field:ownerunit itemname="业主单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ownerunit>

<field:buildingA itemname="建筑设计" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:buildingA>

<field:partnercorp itemname="合作单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:partnercorp>

<field:chiefarchitect itemname="总建筑师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:chiefarchitect>

<field:designteam itemname="设计团队" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:designteam>

<field:roomdesign itemname="室内设计" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:roomdesign>

<field:floorage itemname="建筑面积" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:floorage>

<field:photograph itemname="建筑摄影" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:photograph>

<field:city itemname="城市" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:city>

<field:picshowhow itemname="图片显示方式" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="none,row,column"  maxlength="250" page="">
</field:picshowhow>

<field:pictype itemname="图片方式" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="1,2,3"  maxlength="250" page="">
</field:pictype>







