<?php
$z[0]=Array("arcurl","",9,24);
$z[0][4]=array();
$z[1]=Array("litpic","",88,103);
$z[1][4]=array();
$z[2]=Array("pubdate","",165,211);
$z[2][4]=array();
$z[2][4]['function']="strftime('%b',@me)";
$z[3]=Array("pubdate","",234,280);
$z[3][4]=array();
$z[3][4]['function']="strftime('%d',@me)";
$z[4]=Array("fulltitle","",389,407);
$z[4][4]=array();
$z[5]=Array("description","",455,489);
$z[5][4]=array();
$z[5][4]['infolen']="150";

?>