<div class="swiper-slide"
             data-select-type="[field:type/]"
        >
          <a href="[field:piclinks/]"
             title="[field:title/]"
             target="_blank"
          >
            <div class="banner_v_wrapper">
              <div class="banner_img">
                <img src="[field:litpic/]" alt="">
              </div>
              <video class="banner_video" width="100%" height="100%" loop muted autoplay>
                <source src="[field:video/]" type="video/mp4">
              </video>
              <div class="banner_text ani"
                   swiper-animate-effect="fadeInUp"
                   swiper-animate-duration="0.5s"
                   swiper-animate-delay="0.3s"
              >
                <div class="banner_text_title">
                  <p>[field:fulltitle/]</p>
                </div>
                <div class="banner_text_desT">
                  <div class="banner_text_desLine"></div>
                  <p>[field:description/]</p>
                </div>
              </div>
            </div>
          </a>
        </div>