{dede:list pagesize ='10' addfields='city, project_name,picshowhow,pictype,list_pic' channelid='18'}
        <a href="[field:arcurl/]">
          <div class="project_list_pic">
            <div></div>
            <img src="[field:list_pic/]" alt="">
          </div>
          <div class="project_list_title">
            <p>[field:title/] / [field:shorttitle/]</p>
            <p>[field:description/]</p>
          </div>
        </a>
        {/dede:list}