<?php
$z[0]=Array("list","\r\n        <a href=\"[field:arcurl/]\">\r\n          <div class=\"project_list_pic\">\r\n            <div></div>\r\n            <img src=\"[field:list_pic/]\" alt=\"\">\r\n          </div>\r\n          <div class=\"project_list_title\">\r\n            <p>[field:title/] / [field:shorttitle/]</p>\r\n            <p>[field:description/]</p>\r\n          </div>\r\n        </a>\r\n        ",0,467);
$z[0][4]=array();
$z[0][4]['pagesize']="10";
$z[0][4]['addfields']="city, project_name,picshowhow,pictype,list_pic";
$z[0][4]['channelid']="18";

?>