<a href="#">
          <div class="project_list_pic">
            <div></div>
            <img src="/templets/hsjzsj/src/assets/projects/project_list_test.jpg" alt="">
          </div>
          <div class="project_list_title">
            <p>山与海的乐章 | 世茂·印山海 / HILLS AND OCEAN，SHIMAO</p>
            <p>天宏海阔层峦叠翠的静谧岛屿之上，日复一日呈现“浮光跃金，静影沉璧”的场景。从基地远望，云雾中群峰渐隐，层层退晕出流动的山形，海水击岸，山形的曲线与海面的波纹如对话般。</p>
          </div>
        </a>