<?php
$z[0]=Array("arcurl","",14,29);
$z[0][4]=array();
$z[1]=Array("litpic","",97,112);
$z[1][4]=array();
$z[2]=Array("pubdate","",174,220);
$z[2][4]=array();
$z[2][4]['function']="strftime('%b',@me)";
$z[3]=Array("pubdate","",243,289);
$z[3][4]=array();
$z[3][4]['function']="strftime('%d',@me)";
$z[4]=Array("fulltitle","",398,416);
$z[4][4]=array();
$z[5]=Array("description","",464,514);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me, 80)";

?>