<div class="team_o_item" onclick="tInfo(index)">

          <div class="team_img">
            <img src="[field:picname/]" alt="">
          </div>

          <div class="team_o_info">
            <div class="team_o_name">
              <h3>[field:name /]</h3>
              <p>[field:engname /]</p>
            </div>

            <div class="team_o_position">
              <h4>
                [field:position /]
              </h4>
              <p>
                [field:eng_position /]
              </p>
            </div>
          </div>

          <div class="clear"></div>

        </div>