<?php
$z[0]=Array("field","",210,233);
$z[0][4]=array();
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",233,253);
$z[1][4]=array();
$z[1][4]['name']="title";
$z[2]=Array("include","",511,548);
$z[2][4]=array();
$z[2][4]['filename']="header.htm";
$z[3]=Array("channel","\r\n        <b>\r\n          <span>|</span>\r\n          <a href=\"[field:typelink/]\">\r\n            <p>[field:typename/]</p>\r\n          </a>\r\n        </b>\r\n        ",941,1255);
$z[3][4]=array();
$z[3][4]['reid']="5";
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<b><span>|</span><a href='~typelink~' ~rel~ class='onActive'>~typename~</a></b>";
$z[4]=Array("arclist","\r\n        <a href=\"[field:arcurl/]\" class=\"item\">\r\n          <div class=\"project_list_pic\">\r\n            <div class=\"project_pic_bg\"></div>\r\n            <img src=\"[field:list_pic function='GetOneImgUrl(@me,0)'/] \" alt=\"\">\r\n          </div>\r\n          <div class=\"project_list_title\">\r\n            <p>[field:title/] / [field:shorttitle/]</p>\r\n            <p>[field:description/]</p>\r\n          </div>\r\n        </a>\r\n        ",1367,1908);
$z[4][4]=array();
$z[4][4]['pagesize']="10";
$z[4][4]['addfields']="city, project_name,picshowhow,pictype,list_pic";
$z[4][4]['channelid']="18";
$z[5]=Array("pagelist","",2018,2052);
$z[5][4]=array();
$z[5][4]['listitem']="pageno";
$z[6]=Array("include","",2137,2174);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>