<?php
$z[0]=Array("field","",210,233);
$z[0][4]=array();
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",234,254);
$z[1][4]=array();
$z[1][4]['name']="title";
$z[2]=Array("include","",512,549);
$z[2][4]=array();
$z[2][4]['filename']="header.htm";
$z[3]=Array("channel","\r\n        <b>\r\n          <span>|</span>\r\n          <a href=\"[field:typelink/]\">\r\n            <p>[field:typename/]</p>\r\n          </a>\r\n        </b>\r\n        ",942,1256);
$z[3][4]=array();
$z[3][4]['reid']="5";
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<b><span>|</span><a href='~typelink~' ~rel~ class='onActive'>~typename~</a></b>";
$z[4]=Array("list","\r\n        <a href=\"[field:arcurl/]\">\r\n          <div class=\"project_list_pic\">\r\n            <div></div>\r\n            <img src=\"[field:picname/]\" alt=\"\">\r\n          </div>\r\n          <div class=\"project_list_title\">\r\n            <p>[field:title/] / [field:shorttitle/]</p>\r\n            <p>[field:description/]</p>\r\n          </div>\r\n        </a>\r\n        ",1350,1742);
$z[4][4]=array();
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",1852,1886);
$z[5][4]=array();
$z[5][4]['listitem']="pageno";
$z[6]=Array("include","",1971,2008);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>